server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://plandeathdb.c3fxvh11ftpt.ap-northeast-2.rds.amazonaws.com:3306/plandeathdb
    username: root
    password: rootroot
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  main:
    allow-bean-definition-overriding: true
  mvc:
    resources:
      static-locations: classpath:/static
    static-path-pattern: /static/**

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

openai:
  api: https://api.openai.com
  key: ${OPENAI_API_KEY}

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
        springframework:
          web: ERROR
